---
title: "Overview"
output:
  html_document:
    number_sections: true
    toc: true
    toc_depth: 2
---

# Challenge

```{r, results="asis"}
cat(configurationYaml$description)
```

# Important Dates

All key dates and organisation phases of the challenge can be found in the tab `Phases`: competition start, competition end, number of phases... 

# Get started

1. Create an account on the codalab platform.

2. Go on the challenge page, in the tab `Participate` and register to get access to the challenge.

3. After approval, if required, constitute teams and design a team coordinator on the platform.

4. Read the overview of the challenge in the tab `Learn the Details`, in the menu `Overview`.

5. Download the starting kit containing the public data sets in the tab `Participate`, in the item `Files`.

6. On your local machine, unzip the just downloaded zip file `stating_kit.zip`. 
The unziped `starting_kit` directory contains :
- A `submission_script.R` to modify and to use to submit your predictions.
- The public data sets (`data_train.rds` and `data_test.rds` files).

7. Then open R in the `starting_kit` directory, (e.g. open `submission_script.R` with RStudio), and launch the following command to generate the baseline submission as a zip file:

```
source("submission_script.R")
```

Alternatively you can generate the baseline submission zip file with the Rscript command: 

```
Rscript submission_script.R
```
The command will produce 2 files located in the folder "starting_kit/submissions"
-results_XXX_XX_XX-XX.zip
-program_XXX_XX_XX-XX.zip


8. You can submit your `results_XXX_XX_XX-XX.zip` or your `program_XXX_XX_XX-XX.zip` file located in `starting_kit/submissions` in the tab `Participate`, in the item `Submit / View Results`.

9. Check the leaderboard in the tab `Results`.

**Please use the `submission_script.R` contained in the `starting_kit` folder as a template to write, run and submit your code.**

# Public Submissions

To share your submissions with other participants, you can mark your submission as public in the tab `Participate`, in the item `Submit / View Results`.

By clicking on the blue cross at the right of your submission, you have additional informations on your submission and the button to make it public.

You can access to all the public submissions of the competition in the tab `Public Submissions`.

# Forum

If enable, you can access to the internal forum in the tab `Forums`.

